name: CD (Deploy to EC2)

on:
  push:
    branches: [ "main" ]

jobs:
  
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            # EC2の中で実行されるコマンドたち
            cd useless-hello-world
            
            # 1. 最新のコードを取ってくる
            git pull origin main
            
            # 2. 再ビルドして起動（バックグラウンド）
            # sudo は usermod してるから不要なはずだけど、念のためなくても動くか確認済み
            sudo docker compose up -d --build
            
            # 3. 古いイメージのお掃除（ディスク節約）
            docker image prune -f